import SwiftUI

extension AppTheme {
    static let all: [AppTheme] = [
        AppTheme(id: "blue", name: "Sky Blue", accentColorName: "BlueAccentColor", textColorName: "BlueTextColor", secondTextColorName: "BlueSecondColor", backColor1: "BlueBackColor1", backColor2: "BlueBackColor2", backColor3: "BlueBackColor3", backColor4: "BlueBackColor4", backImage: "BlueBackImage", gradient: LinearGradient(colors: [Color("BlueBackColor1"), Color("BlueBackColor4")], startPoint: .top, endPoint: .bottom)),
        AppTheme(id: "purple", name: "Lavender", accentColorName: "PurpleAccentColor", textColorName: "PurpleTextColor", secondTextColorName: "PurpleSecondColor", backColor1: "PurpleBackColor1", backColor2: "PurpleBackColor2", backColor3: "PurpleBackColor3", backColor4: "PurpleBackColor4", backImage: "PurpleBackImage", gradient: LinearGradient(colors: [Color("PurpleBackColor1"), Color("PurpleBackColor4")], startPoint: .top, endPoint: .bottom)),
        AppTheme(id: "yellow", name: "Sunset", accentColorName: "YellowAccentColor", textColorName: "YellowTextColor", secondTextColorName: "YellowSecondColor", backColor1: "YellowBackColor1", backColor2: "YellowBackColor2", backColor3: "YellowBackColor3", backColor4: "YellowBackColor4", backImage: "YellowBackImage", gradient: LinearGradient(colors: [Color("YellowBackColor1"), Color("YellowBackColor4")], startPoint: .top, endPoint: .bottom)),
        AppTheme(id: "green", name: "Forest", accentColorName: "GreenAccentColor", textColorName: "GreenTextColor", secondTextColorName: "GreenSecondColor", backColor1: "GreenBackColor1", backColor2: "GreenBackColor2", backColor3: "GreenBackColor3", backColor4: "GreenBackColor4", backImage: "GreenBackImage", gradient: LinearGradient(colors: [Color("GreenBackColor1"), Color("GreenBackColor4")], startPoint: .top, endPoint: .bottom)),
        AppTheme(id: "white", name: "Midnight", accentColorName: "WhiteAccentColor", textColorName: "WhiteTextColor", secondTextColorName: "WhiteSecondColor", backColor1: "WhiteBackColor1", backColor2: "WhiteBackColor2", backColor3: "WhiteBackColor3", backColor4: "WhiteBackColor4", backImage: "WhiteBackImage", gradient: LinearGradient(colors: [Color("WhiteBackColor1"), Color("WhiteBackColor4")], startPoint: .top, endPoint: .bottom)),
        AppTheme(id: "deepblue", name: "Beach Sea", accentColorName: "DeepAccentColor", textColorName: "DeepTextColor", secondTextColorName: "DeepSecondColor", backColor1: "DeepBackColor1", backColor2: "DeepBackColor2", backColor3: "DeepBackColor3", backColor4: "DeepBackColor4", backImage: "DeepBackImage", gradient: LinearGradient(colors: [Color("WhiteBackColor1"), Color("WhiteBackColor4")], startPoint: .top, endPoint: .bottom))
    ]
}
